# ===================== PAL1 脚本操作码定义 =====================
# 基于 sdlpal 项目参考仙剑奇侠传一代脚本格式
# opcode = uint16le，每个参数 = uint16le

OPCODE_INFO = {
    0x00: {"name": "STOP",          "args": 0, "desc": "终止脚本"},
    0x01: {"name": "TALK",          "args": 1, "desc": "显示对话（word=对话编号）"},
    0x02: {"name": "WAIT_KEY",      "args": 0, "desc": "等待玩家按键"},
    0x03: {"name": "SET_MONEY",     "args": 1, "desc": "设置金钱数量"},
    0x04: {"name": "SET_ATTR",      "args": 2, "desc": "设置角色属性（角色ID, 属性值）"},
    0x05: {"name": "CHECK_ITEM",    "args": 2, "desc": "检查物品（物品ID, 数量）"},
    0x06: {"name": "ADD_ITEM",      "args": 2, "desc": "增减物品（物品ID, 数量）"},
    0x07: {"name": "SET_HPMP",      "args": 3, "desc": "修改HP/MP（角色ID, HP, MP）"},
    0x08: {"name": "SET_LEVEL",     "args": 2, "desc": "修改角色等级（角色ID, 等级）"},
    0x09: {"name": "MENU",          "args": 1, "desc": "显示菜单（word=菜单编号）"},
    0x0A: {"name": "SHOP",          "args": 1, "desc": "显示商店（word=商店编号）"},
    0x0B: {"name": "TEAM",          "args": 0, "desc": "显示队友选择"},
    0x0C: {"name": "RESUME_MUSIC",  "args": 0, "desc": "恢复场景音乐"},
    0x0D: {"name": "PLAY_MIDI",     "args": 1, "desc": "播放 MIDI（word=MIDI编号）"},
    0x0E: {"name": "BATTLE",        "args": 1, "desc": "进入战斗（word=战斗编号）"},
    0x0F: {"name": "PAL_FADE",      "args": 1, "desc": "调色板渐变（word=编号）"},
    0x10: {"name": "CHANGE_SCENE",  "args": 2, "desc": "切换场景（场景ID, 位置）"},
    0x11: {"name": "WALK",          "args": 2, "desc": "角色行走（角色ID, 方向）"},
    0x12: {"name": "RUN",           "args": 2, "desc": "角色跑动（角色ID, 方向）"},
    0x13: {"name": "SLEEP",         "args": 1, "desc": "等待（word=帧数）"},
    0x14: {"name": "SHAKE",         "args": 1, "desc": "屏幕震动（word=强度）"},
    0x15: {"name": "SCROLL",        "args": 1, "desc": "设置屏幕卷动（word=方向）"},
    0x16: {"name": "FACE",          "args": 1, "desc": "显示头像（word=头像编号）"},
    0x17: {"name": "PICTURE",       "args": 1, "desc": "显示图片（word=图片编号）"},
    0x18: {"name": "ANIMATION",     "args": 2, "desc": "显示动画（编号, 位置）"},
    0x19: {"name": "MUSIC_FADE",    "args": 2, "desc": "音乐渐变（编号, 速度）"},
    0x1A: {"name": "PAUSE_MUSIC",   "args": 0, "desc": "暂停音乐"},
    0x1B: {"name": "RESUME_MUSIC2", "args": 0, "desc": "恢复音乐"},
    0x1C: {"name": "SET_TEAM",      "args": 2, "desc": "设置队友（角色ID, 状态）"},
    0x1D: {"name": "PLAY_SOUND",    "args": 1, "desc": "播放音效（word=音效编号）"},
    0x1E: {"name": "CHECK_MONEY",   "args": 1, "desc": "检查金钱（word=数量）"},
    0x1F: {"name": "CHECK_LEVEL",   "args": 2, "desc": "检查角色等级（角色ID, 等级）"},
    0x20: {"name": "NAME",          "args": 1, "desc": "显示角色姓名（word=角色ID）"},
    0x21: {"name": "SET_ATK",       "args": 2, "desc": "修改攻击力（角色ID, 值）"},
    0x22: {"name": "SET_DEF",       "args": 2, "desc": "修改防御力（角色ID, 值）"},
    0x23: {"name": "SET_AGI",       "args": 2, "desc": "修改身法（角色ID, 值）"},
    0x24: {"name": "SET_STATUS",    "args": 2, "desc": "设置角色状态（角色ID, 状态）"},
    0x25: {"name": "JUMP",          "args": 1, "desc": "无条件跳转（word=偏移地址）"},
    0x26: {"name": "JUMP_IF",       "args": 2, "desc": "条件跳转（条件, 偏移地址）"},
    0x27: {"name": "SET_OBJ",       "args": 2, "desc": "设置对象状态（对象ID, 状态）"},
    0x28: {"name": "CHECK_OBJ",     "args": 2, "desc": "检查对象状态（对象ID, 状态）"},
    0x29: {"name": "TRAP",          "args": 1, "desc": "设置陷阱（word=陷阱编号）"},
    0x2A: {"name": "SCRIPT",        "args": 1, "desc": "执行脚本（word=脚本编号）"},
    0x2B: {"name": "SET_POS",       "args": 3, "desc": "设置角色位置（角色ID, X, Y）"},
    0x2C: {"name": "WAIT_WALK",     "args": 1, "desc": "等待角色移动完成（角色ID）"},
    0x2D: {"name": "SET_DIR",       "args": 2, "desc": "设置角色方向（角色ID, 方向）"},
    0x2E: {"name": "GET_ITEM",      "args": 2, "desc": "显示获得物品（物品ID, 数量）"},
    0x2F: {"name": "SAVE",          "args": 0, "desc": "保存游戏"},
    0x30: {"name": "LOAD",          "args": 0, "desc": "加载存档"},
    0x31: {"name": "TITLE",         "args": 0, "desc": "显示标题画面"},
    0x32: {"name": "GAME_OVER",     "args": 0, "desc": "游戏结束"},
    0x33: {"name": "SHOP_EX",       "args": 2, "desc": "高级商店（编号, 选项）"},
    0x34: {"name": "CHOICE",        "args": 1, "desc": "显示选择支（word=编号）"},
    0x35: {"name": "STATUS",        "args": 1, "desc": "显示角色属性（角色ID）"},
    0x36: {"name": "TEAM_STATUS",   "args": 0, "desc": "显示队伍状态"},
    0x37: {"name": "CONFIG",        "args": 0, "desc": "显示游戏设置"},
    0x38: {"name": "CHECK_TEAM",    "args": 1, "desc": "检查队友（角色ID）"},
    0x39: {"name": "SET_EXP",       "args": 2, "desc": "设置角色经验（角色ID, 经验）"},
    0x3A: {"name": "LEVEL_UP",      "args": 1, "desc": "角色升级（角色ID）"},
    0x3B: {"name": "SKILL",         "args": 1, "desc": "显示角色技能（角色ID）"},
    0x3C: {"name": "EQUIP",         "args": 1, "desc": "显示角色装备（角色ID）"},
    0x3D: {"name": "USE_ITEM",      "args": 1, "desc": "使用物品（物品ID）"},
    0x3E: {"name": "LEAVE",         "args": 1, "desc": "角色离队（角色ID）"},
    0x3F: {"name": "JOIN",          "args": 1, "desc": "角色加入（角色ID）"},
    0x40: {"name": "SET_MAGIC",     "args": 2, "desc": "修改角色仙术（角色ID, 仙术ID）"},
    0x41: {"name": "LIST",          "args": 0, "desc": "显示角色列表"},
    0x42: {"name": "SELECT",        "args": 1, "desc": "显示角色选择（标题）"},
    0x43: {"name": "INPUT_NAME",    "args": 1, "desc": "角色名输入（角色ID）"},
    0x44: {"name": "TALK_EX",       "args": 1, "desc": "高级对话（word=对话编号）"},
    0x45: {"name": "MSG",           "args": 1, "desc": "显示系统消息（word=消息编号）"},
    0x46: {"name": "ANIM_SCENE",    "args": 2, "desc": "场景动画（编号, 位置）"},
    0x47: {"name": "CHECK_STATUS",  "args": 2, "desc": "检查角色状态（角色ID, 状态）"},
    0x48: {"name": "CG",            "args": 1, "desc": "显示CG（word=CG编号）"},
    0x49: {"name": "FACE_EX",       "args": 1, "desc": "高级头像显示（word=编号）"},
    0x4A: {"name": "SET_APPEAR",    "args": 2, "desc": "设置角色外观（角色ID, 外观ID）"},
    0x4B: {"name": "WALK_SPRITE",   "args": 1, "desc": "显示行走图（word=编号）"},
    0x4C: {"name": "SET_SPEED",     "args": 2, "desc": "设置角色速度（角色ID, 速度）"},
    0x4D: {"name": "MOVE_PATH",     "args": 3, "desc": "移动路径（角色ID, 路径ID, 速度）"},
    0x4E: {"name": "FOLLOW",        "args": 2, "desc": "设置跟随（角色ID, 目标ID）"},
    0x4F: {"name": "BATTLE_ANIM",   "args": 2, "desc": "战斗动作（角色ID, 动作编号）"},
    0x50: {"name": "BATTLE_EFFECT", "args": 2, "desc": "战斗特效（编号, 位置）"},
    0x51: {"name": "BATTLE_ATTR",   "args": 3, "desc": "战斗属性（角色ID, 属性, 值）"},
    0x52: {"name": "BATTLE_SKILL",  "args": 2, "desc": "战斗技能（角色ID, 技能ID）"},
    0x53: {"name": "BATTLE_ITEM",   "args": 2, "desc": "战斗物品（角色ID, 物品ID）"},
    0x54: {"name": "ESCAPE",        "args": 0, "desc": "战斗逃跑"},
    0x55: {"name": "SET_AI",        "args": 2, "desc": "设置AI（角色ID, AI编号）"},
    0x56: {"name": "BATTLE_RESULT", "args": 0, "desc": "显示战斗结果"},
    0x57: {"name": "BATTLE_EXP",    "args": 1, "desc": "战斗经验（值）"},
    0x58: {"name": "BATTLE_MONEY",  "args": 1, "desc": "战斗金钱（值）"},
    0x59: {"name": "BATTLE_DROP",   "args": 2, "desc": "战斗掉落（物品ID, 数量）"},
    0x5A: {"name": "BATTLE_LEVEL",  "args": 1, "desc": "战斗等级（值）"},
    0x5B: {"name": "BATTLE_STATUS", "args": 2, "desc": "战斗状态（角色ID, 状态）"},
    0x5C: {"name": "REVIVE",        "args": 1, "desc": "角色复活（角色ID）"},
    0x5D: {"name": "DEAD",          "args": 1, "desc": "角色死亡（角色ID）"},
    0x5E: {"name": "BATTLE_HP",     "args": 2, "desc": "战斗HP（角色ID, 值）"},
    0x5F: {"name": "BATTLE_MP",     "args": 2, "desc": "战斗MP（角色ID, 值）"},
    0x60: {"name": "BATTLE_ATK",    "args": 2, "desc": "战斗攻击力（角色ID, 值）"},
    0x61: {"name": "BATTLE_DEF",    "args": 2, "desc": "战斗防御力（角色ID, 值）"},
    0x62: {"name": "BATTLE_AGI",    "args": 2, "desc": "战斗身法（角色ID, 值）"},
    0x63: {"name": "BATTLE_MAGIC",  "args": 2, "desc": "战斗仙术（角色ID, 仙术ID）"},
    0x64: {"name": "BATTLE_TOOL",   "args": 2, "desc": "战斗道具（角色ID, 道具ID）"},
    0x65: {"name": "BATTLE_EQUIP",  "args": 2, "desc": "战斗装备（角色ID, 装备ID）"},
    0x66: {"name": "LEARN_SKILL",   "args": 2, "desc": "学习技能（角色ID, 技能ID）"},
    0x67: {"name": "FORGET_SKILL",  "args": 2, "desc": "遗忘技能（角色ID, 技能ID）"},
    0x68: {"name": "UPGRADE_SKILL", "args": 2, "desc": "技能升级（角色ID, 技能ID）"},
    0x69: {"name": "DOWNGRADE_SKILL","args": 2, "desc": "技能降级（角色ID, 技能ID）"},
    0x6A: {"name": "RESET_SKILL",   "args": 1, "desc": "技能重置（角色ID）"},
    0x6B: {"name": "COPY_SKILL",    "args": 2, "desc": "技能复制（源ID, 目标ID）"},
    0x6C: {"name": "SWAP_SKILL",    "args": 2, "desc": "技能交换（角色ID1, 角色ID2）"},
    0x6D: {"name": "MERGE_SKILL",   "args": 2, "desc": "技能合并（角色ID1, 角色ID2）"},
    0x6E: {"name": "SPLIT_SKILL",   "args": 2, "desc": "技能分解（角色ID, 技能ID）"},
    0x6F: {"name": "INHERIT_SKILL", "args": 2, "desc": "技能传承（源ID, 目标ID）"},
    0x70: {"name": "AWAKEN_SKILL",  "args": 2, "desc": "技能觉醒（角色ID, 技能ID）"},
    0x71: {"name": "SEAL_SKILL",    "args": 2, "desc": "技能封印（角色ID, 技能ID）"},
    0x72: {"name": "UNSEAL_SKILL",  "args": 2, "desc": "技能解封（角色ID, 技能ID）"},
    0x73: {"name": "AWAKEN",        "args": 2, "desc": "角色觉醒（角色ID, 觉醒ID）"},
    0x74: {"name": "TRANSFORM",     "args": 2, "desc": "角色变身（角色ID, 变身ID）"},
    0x75: {"name": "FUSION",        "args": 2, "desc": "角色合体（角色ID1, 角色ID2）"},
    0x76: {"name": "SEPARATION",    "args": 2, "desc": "角色分离（角色ID1, 角色ID2）"},
    0x77: {"name": "SUMMON",        "args": 2, "desc": "召唤（角色ID, 召唤ID）"},
    0x78: {"name": "DISPEL",        "args": 2, "desc": "驱散（角色ID, 目标ID）"},
    0x79: {"name": "PURIFY",        "args": 2, "desc": "净化（角色ID, 目标ID）"},
    0x7A: {"name": "BLESS",         "args": 2, "desc": "祝福（角色ID, 目标ID）"},
    0x7B: {"name": "CURSE",         "args": 2, "desc": "诅咒（角色ID, 目标ID）"},
    0x7C: {"name": "SEAL",          "args": 2, "desc": "封印（角色ID, 目标ID）"},
    0x7D: {"name": "UNSEAL",        "args": 2, "desc": "解封（角色ID, 目标ID）"},
    0x7E: {"name": "AWAKEN_EX",     "args": 2, "desc": "高级觉醒（角色ID, 觉醒ID）"},
    0x7F: {"name": "TRANSFORM_EX",  "args": 2, "desc": "高级变身（角色ID, 变身ID）"},
    0x80: {"name": "FUSION_EX",     "args": 2, "desc": "高级合体（角色ID1, 角色ID2）"},
    0x81: {"name": "SEPARATION_EX", "args": 2, "desc": "高级分离（角色ID1, 角色ID2）"},
    0x82: {"name": "SUMMON_EX",     "args": 2, "desc": "高级召唤（角色ID, 召唤ID）"},
    0x83: {"name": "DISPEL_EX",     "args": 2, "desc": "高级驱散（角色ID, 目标ID）"},
    0x84: {"name": "PURIFY_EX",     "args": 2, "desc": "高级净化（角色ID, 目标ID）"},
    0x85: {"name": "BLESS_EX",      "args": 2, "desc": "高级祝福（角色ID, 目标ID）"},
    0x86: {"name": "CURSE_EX",      "args": 2, "desc": "高级诅咒（角色ID, 目标ID）"},
    0x87: {"name": "SEAL_EX",       "args": 2, "desc": "高级封印（角色ID, 目标ID）"},
    0x88: {"name": "UNSEAL_EX",     "args": 2, "desc": "高级解封（角色ID, 目标ID）"},
    0x89: {"name": "AWAKEN_EX2",    "args": 2, "desc": "超级觉醒（角色ID, 觉醒ID）"},
    0x8A: {"name": "TRANSFORM_EX2", "args": 2, "desc": "超级变身（角色ID, 变身ID）"},
    0x8B: {"name": "FUSION_EX2",    "args": 2, "desc": "超级合体（角色ID1, 角色ID2）"},
    0x8C: {"name": "SEPARATION_EX2","args": 2, "desc": "超级分离（角色ID1, 角色ID2）"},
    0x8D: {"name": "SUMMON_EX2",    "args": 2, "desc": "超级召唤（角色ID, 召唤ID）"},
    0x8E: {"name": "DISPEL_EX2",    "args": 2, "desc": "超级驱散（角色ID, 目标ID）"},
    0x8F: {"name": "PURIFY_EX2",    "args": 2, "desc": "超级净化（角色ID, 目标ID）"},
    0x90: {"name": "BLESS_EX2",     "args": 2, "desc": "超级祝福（角色ID, 目标ID）"},
    0x91: {"name": "CURSE_EX2",     "args": 2, "desc": "超级诅咒（角色ID, 目标ID）"},
    0x92: {"name": "SEAL_EX2",      "args": 2, "desc": "超级封印（角色ID, 目标ID）"},
    0x93: {"name": "UNSEAL_EX2",    "args": 2, "desc": "超级解封（角色ID, 目标ID）"},
    0x94: {"name": "AWAKEN_EX3",    "args": 2, "desc": "究极觉醒（角色ID, 觉醒ID）"},
    0x95: {"name": "TRANSFORM_EX3", "args": 2, "desc": "究极变身（角色ID, 变身ID）"},
    0x96: {"name": "FUSION_EX3",    "args": 2, "desc": "究极合体（角色ID1, 角色ID2）"},
    0x97: {"name": "SEPARATION_EX3","args": 2, "desc": "究极分离（角色ID1, 角色ID2）"},
    0x98: {"name": "SUMMON_EX3",    "args": 2, "desc": "究极召唤（角色ID, 召唤ID）"},
    0x99: {"name": "DISPEL_EX3",    "args": 2, "desc": "究极驱散（角色ID, 目标ID）"},
    0x9A: {"name": "PURIFY_EX3",    "args": 2, "desc": "究极净化（角色ID, 目标ID）"},
    0x9B: {"name": "BLESS_EX3",     "args": 2, "desc": "究极祝福（角色ID, 目标ID）"},
    0x9C: {"name": "CURSE_EX3",     "args": 2, "desc": "究极诅咒（角色ID, 目标ID）"},
    0x9D: {"name": "SEAL_EX3",      "args": 2, "desc": "究极封印（角色ID, 目标ID）"},
    0x9E: {"name": "UNSEAL_EX3",    "args": 2, "desc": "究极解封（角色ID, 目标ID）"},
    0x9F: {"name": "AWAKEN_EX4",    "args": 2, "desc": "神级觉醒（角色ID, 觉醒ID）"},
    0xA0: {"name": "TRANSFORM_EX4", "args": 2, "desc": "神级变身（角色ID, 变身ID）"},
    0xA1: {"name": "FUSION_EX4",    "args": 2, "desc": "神级合体（角色ID1, 角色ID2）"},
    0xA2: {"name": "SEPARATION_EX4","args": 2, "desc": "神级分离（角色ID1, 角色ID2）"},
    0xA3: {"name": "SUMMON_EX4",    "args": 2, "desc": "神级召唤（角色ID, 召唤ID）"},
    0xA4: {"name": "DISPEL_EX4",    "args": 2, "desc": "神级驱散（角色ID, 目标ID）"},
    0xA5: {"name": "PURIFY_EX4",    "args": 2, "desc": "神级净化（角色ID, 目标ID）"},
    0xA6: {"name": "BLESS_EX4",     "args": 2, "desc": "神级祝福（角色ID, 目标ID）"},
    0xA7: {"name": "CURSE_EX4",     "args": 2, "desc": "神级诅咒（角色ID, 目标ID）"},
    0xA8: {"name": "SEAL_EX4",      "args": 2, "desc": "神级封印（角色ID, 目标ID）"},
    0xA9: {"name": "UNSEAL_EX4",    "args": 2, "desc": "神级解封（角色ID, 目标ID）"},
    0xAA: {"name": "AWAKEN_EX5",    "args": 2, "desc": "终极觉醒（角色ID, 觉醒ID）"},
    0xAB: {"name": "TRANSFORM_EX5", "args": 2, "desc": "终极变身（角色ID, 变身ID）"},
    0xAC: {"name": "FUSION_EX5",    "args": 2, "desc": "终极合体（角色ID1, 角色ID2）"},
    0xAD: {"name": "SEPARATION_EX5","args": 2, "desc": "终极分离（角色ID1, 角色ID2）"},
    0xAE: {"name": "SUMMON_EX5",    "args": 2, "desc": "终极召唤（角色ID, 召唤ID）"},
    0xAF: {"name": "DISPEL_EX5",    "args": 2, "desc": "终极驱散（角色ID, 目标ID）"},
    0xB0: {"name": "PURIFY_EX5",    "args": 2, "desc": "终极净化（角色ID, 目标ID）"},
    0xB1: {"name": "BLESS_EX5",     "args": 2, "desc": "终极祝福（角色ID, 目标ID）"},
    0xB2: {"name": "CURSE_EX5",     "args": 2, "desc": "终极诅咒（角色ID, 目标ID）"},
    0xB3: {"name": "SEAL_EX5",      "args": 2, "desc": "终极封印（角色ID, 目标ID）"},
    0xB4: {"name": "UNSEAL_EX5",    "args": 2, "desc": "终极解封（角色ID, 目标ID）"},
    0xB5: {"name": "AWAKEN_EX6",    "args": 2, "desc": "超神觉醒（角色ID, 觉醒ID）"},
    0xB6: {"name": "TRANSFORM_EX6", "args": 2, "desc": "超神变身（角色ID, 变身ID）"},
    0xB7: {"name": "FUSION_EX6",    "args": 2, "desc": "超神合体（角色ID1, 角色ID2）"},
    0xB8: {"name": "SEPARATION_EX6","args": 2, "desc": "超神分离（角色ID1, 角色ID2）"},
    0xB9: {"name": "SUMMON_EX6",    "args": 2, "desc": "超神召唤（角色ID, 召唤ID）"},
    0xBA: {"name": "DISPEL_EX6",    "args": 2, "desc": "超神驱散（角色ID, 目标ID）"},
    0xBB: {"name": "PURIFY_EX6",    "args": 2, "desc": "超神净化（角色ID, 目标ID）"},
    0xBC: {"name": "BLESS_EX6",     "args": 2, "desc": "超神祝福（角色ID, 目标ID）"},
    0xBD: {"name": "CURSE_EX6",     "args": 2, "desc": "超神诅咒（角色ID, 目标ID）"},
    0xBE: {"name": "SEAL_EX6",      "args": 2, "desc": "超神封印（角色ID, 目标ID）"},
    0xBF: {"name": "UNSEAL_EX6",    "args": 2, "desc": "超神解封（角色ID, 目标ID）"},
    0xC0: {"name": "AWAKEN_EX7",    "args": 2, "desc": "传说觉醒（角色ID, 觉醒ID）"},
    0xC1: {"name": "TRANSFORM_EX7", "args": 2, "desc": "传说变身（角色ID, 变身ID）"},
    0xC2: {"name": "FUSION_EX7",    "args": 2, "desc": "传说合体（角色ID1, 角色ID2）"},
    0xC3: {"name": "SEPARATION_EX7","args": 2, "desc": "传说分离（角色ID1, 角色ID2）"},
    0xC4: {"name": "SUMMON_EX7",    "args": 2, "desc": "传说召唤（角色ID, 召唤ID）"},
    0xC5: {"name": "DISPEL_EX7",    "args": 2, "desc": "传说驱散（角色ID, 目标ID）"},
    0xC6: {"name": "PURIFY_EX7",    "args": 2, "desc": "传说净化（角色ID, 目标ID）"},
    0xC7: {"name": "BLESS_EX7",     "args": 2, "desc": "传说祝福（角色ID, 目标ID）"},
    0xC8: {"name": "CURSE_EX7",     "args": 2, "desc": "传说诅咒（角色ID, 目标ID）"},
    0xC9: {"name": "SEAL_EX7",      "args": 2, "desc": "传说封印（角色ID, 目标ID）"},
    0xCA: {"name": "UNSEAL_EX7",    "args": 2, "desc": "传说解封（角色ID, 目标ID）"},
    0xCB: {"name": "AWAKEN_EX8",    "args": 2, "desc": "神话觉醒（角色ID, 觉醒ID）"},
    0xCC: {"name": "TRANSFORM_EX8", "args": 2, "desc": "神话变身（角色ID, 变身ID）"},
    0xCD: {"name": "FUSION_EX8",    "args": 2, "desc": "神话合体（角色ID1, 角色ID2）"},
    0xCE: {"name": "SEPARATION_EX8","args": 2, "desc": "神话分离（角色ID1, 角色ID2）"},
    0xCF: {"name": "SUMMON_EX8",    "args": 2, "desc": "神话召唤（角色ID, 召唤ID）"},
    0xD0: {"name": "DISPEL_EX8",    "args": 2, "desc": "神话驱散（角色ID, 目标ID）"},
    0xD1: {"name": "PURIFY_EX8",    "args": 2, "desc": "神话净化（角色ID, 目标ID）"},
    0xD2: {"name": "BLESS_EX8",     "args": 2, "desc": "神话祝福（角色ID, 目标ID）"},
    0xD3: {"name": "CURSE_EX8",     "args": 2, "desc": "神话诅咒（角色ID, 目标ID）"},
    0xD4: {"name": "SEAL_EX8",      "args": 2, "desc": "神话封印（角色ID, 目标ID）"},
    0xD5: {"name": "UNSEAL_EX8",    "args": 2, "desc": "神话解封（角色ID, 目标ID）"},
    0xD6: {"name": "AWAKEN_EX9",    "args": 2, "desc": "至尊觉醒（角色ID, 觉醒ID）"},
    0xD7: {"name": "TRANSFORM_EX9", "args": 2, "desc": "至尊变身（角色ID, 变身ID）"},
    0xD8: {"name": "FUSION_EX9",    "args": 2, "desc": "至尊合体（角色ID1, 角色ID2）"},
    0xD9: {"name": "SEPARATION_EX9","args": 2, "desc": "至尊分离（角色ID1, 角色ID2）"},
    0xDA: {"name": "SUMMON_EX9",    "args": 2, "desc": "至尊召唤（角色ID, 召唤ID）"},
    0xDB: {"name": "DISPEL_EX9",    "args": 2, "desc": "至尊驱散（角色ID, 目标ID）"},
    0xDC: {"name": "PURIFY_EX9",    "args": 2, "desc": "至尊净化（角色ID, 目标ID）"},
    0xDD: {"name": "BLESS_EX9",     "args": 2, "desc": "至尊祝福（角色ID, 目标ID）"},
    0xDE: {"name": "CURSE_EX9",     "args": 2, "desc": "至尊诅咒（角色ID, 目标ID）"},
    0xDF: {"name": "SEAL_EX9",      "args": 2, "desc": "至尊封印（角色ID, 目标ID）"},
    0xE0: {"name": "UNSEAL_EX9",    "args": 2, "desc": "至尊解封（角色ID, 目标ID）"},
    0xE1: {"name": "AWAKEN_EX10",   "args": 2, "desc": "无上觉醒（角色ID, 觉醒ID）"},
    0xE2: {"name": "TRANSFORM_EX10","args": 2, "desc": "无上变身（角色ID, 变身ID）"},
    0xE3: {"name": "FUSION_EX10",   "args": 2, "desc": "无上合体（角色ID1, 角色ID2）"},
    0xE4: {"name": "SEPARATION_EX10","args": 2, "desc": "无上分离（角色ID1, 角色ID2）"},
    0xE5: {"name": "SUMMON_EX10",   "args": 2, "desc": "无上召唤（角色ID, 召唤ID）"},
    0xE6: {"name": "DISPEL_EX10",   "args": 2, "desc": "无上驱散（角色ID, 目标ID）"},
    0xE7: {"name": "PURIFY_EX10",   "args": 2, "desc": "无上净化（角色ID, 目标ID）"},
    0xE8: {"name": "BLESS_EX10",    "args": 2, "desc": "无上祝福（角色ID, 目标ID）"},
    0xE9: {"name": "CURSE_EX10",    "args": 2, "desc": "无上诅咒（角色ID, 目标ID）"},
    0xEA: {"name": "SEAL_EX10",     "args": 2, "desc": "无上封印（角色ID, 目标ID）"},
    0xEB: {"name": "UNSEAL_EX10",   "args": 2, "desc": "无上解封（角色ID, 目标ID）"},
    0xEC: {"name": "AWAKEN_EX11",   "args": 2, "desc": "宇宙觉醒（角色ID, 觉醒ID）"},
    0xED: {"name": "TRANSFORM_EX11","args": 2, "desc": "宇宙变身（角色ID, 变身ID）"},
    0xEE: {"name": "FUSION_EX11",   "args": 2, "desc": "宇宙合体（角色ID1, 角色ID2）"},
    0xEF: {"name": "SEPARATION_EX11","args": 2, "desc": "宇宙分离（角色ID1, 角色ID2）"},
    0xF0: {"name": "SUMMON_EX11",   "args": 2, "desc": "宇宙召唤（角色ID, 召唤ID）"},
    0xF1: {"name": "DISPEL_EX11",   "args": 2, "desc": "宇宙驱散（角色ID, 目标ID）"},
    0xF2: {"name": "PURIFY_EX11",   "args": 2, "desc": "宇宙净化（角色ID, 目标ID）"},
    0xF3: {"name": "BLESS_EX11",    "args": 2, "desc": "宇宙祝福（角色ID, 目标ID）"},
    0xF4: {"name": "CURSE_EX11",    "args": 2, "desc": "宇宙诅咒（角色ID, 目标ID）"},
    0xF5: {"name": "SEAL_EX11",     "args": 2, "desc": "宇宙封印（角色ID, 目标ID）"},
    0xF6: {"name": "UNSEAL_EX11",   "args": 2, "desc": "宇宙解封（角色ID, 目标ID）"},
    0xF7: {"name": "AWAKEN_EX12",   "args": 2, "desc": "混沌觉醒（角色ID, 觉醒ID）"},
    0xF8: {"name": "TRANSFORM_EX12","args": 2, "desc": "混沌变身（角色ID, 变身ID）"},
    0xF9: {"name": "FUSION_EX12",   "args": 2, "desc": "混沌合体（角色ID1, 角色ID2）"},
    0xFA: {"name": "SEPARATION_EX12","args": 2, "desc": "混沌分离（角色ID1, 角色ID2）"},
    0xFB: {"name": "SUMMON_EX12",   "args": 2, "desc": "混沌召唤（角色ID, 召唤ID）"},
    0xFC: {"name": "DISPEL_EX12",   "args": 2, "desc": "混沌驱散（角色ID, 目标ID）"},
    0xFD: {"name": "PURIFY_EX12",   "args": 2, "desc": "混沌净化（角色ID, 目标ID）"},
    0xFE: {"name": "BLESS_EX12",    "args": 2, "desc": "混沌祝福（角色ID, 目标ID）"},
    0xFF: {"name": "CURSE_EX12",    "args": 2, "desc": "混沌诅咒（角色ID, 目标ID）"},
}
